{% set version = "1.1.2" %}

package:
  name: screed
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/screed/screed-{{ version }}.tar.gz
  sha256: 734ffa7a8a645286496d895b736f91d6b2988956e2fd42358123d93ec8519b6a

build:
  noarch: python
  entry_points:
    - screed = screed.__main__:main
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps -vv .

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=48
    - setuptools_scm
    - setuptools_scm_git_archive

  run:
    - python >=3.7
    - setuptools

test:
  imports:
    - screed
    - screed.tests

  commands:
    - screed --help

  requires:
    - pytest >=6.0
    - pytest-cov

about:
  home: http://github.com/dib-lab/screed/
  license: BSD-3-Clause
  summary: Screed is a biological sequence parsing and storage/retrieval library for DNA and protein sequences.
  license_family: BSD
  license_file: doc/LICENSE.rst
  dev_url: https://github.com/dib-lab/screed
  doc_url: https://screed.readthedocs.io/

extra:
  recipe-maintainers:
    - luizirber
    - ctb
